### ISSUE TITLE
CI run every 6 months

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-local_plugin_template#16]
We should establish a best practice that the CI should run by itself every six months (cron mode) in GitHub Actions.

This will allow it to see if a new version of Moodle was released and then test the existing code against that new version

**Comment by marharyta-morozova** [comment]
@fulldecent this issue resolved

**Comment by fulldecent** [comment]
Done at https://github.com/fulldecent/moodle-local_plugin_template/commit/ff1453963470569ff9aff07d85033d7522236c0d
